---

- name: deploy binary
  copy: src="{{ resources_dir }}/bin/pd-server" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: pd_binary

- name: backup binary file
  command: mv "{{ pd_binary.backup_file }}" "{{ backup_dir }}"
  when: pd_binary.changed and pd_binary.backup_file is defined

- name: create startup script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include_tasks: "{{ process_supervision }}_deployment.yml"
