apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: monitor-fluentd
    release: prometheus-operator
  name: fluentd
  namespace: monitor
spec:
  endpoints:
  - path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
      - monitor
  selector:
    matchLabels:
      app: fluentd
