apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-operator
  name: prometheus-operator-kubernetes-resources
  namespace: monitor
spec:
  groups:
  - name: kubernetes-resources
    rules:
    - alert: KubeCPUOvercommit
      annotations:
        message: Cluster has overcommitted CPU resource requests for Pods and cannot
          tolerate node failure.
      expr: |-
        sum(namespace_name:kube_pod_container_resource_requests_cpu_cores:sum)
          /
        sum(node:node_num_cpu:sum)
          > 0.85
      for: 5m
      labels:
        severity: warning
    - alert: KubeMemOvercommit
      annotations:
        message: Cluster has overcommitted memory resource requests for Pods and cannot
          tolerate node failure.
      expr: |-
        sum(namespace_name:kube_pod_container_resource_requests_memory_bytes:sum)
          /
        sum(node_memory_MemTotal_bytes)
          >
        (count(node:node_num_cpu:sum)-1)
          /
        count(node:node_num_cpu:sum)
      for: 5m
      labels:
        severity: warning
    - alert: CPUThrottlingHigh
      annotations:
        message: 'namespace: {{ $labels.namespace }}, pod: {{ $labels.pod_name }}, container: {{ $labels.container_name }} CPU 已经 throttling 了{{ printf "%0.0f" $value }}%'
      expr: |-
        100 * sum(increase(container_cpu_cfs_throttled_periods_total{container_name!="", }[5m])) by (container_name, pod_name, namespace)
          /
        sum(increase(container_cpu_cfs_periods_total{}[5m])) by (container_name, pod_name, namespace)
          > 40
      for: 15m
      labels:
        severity: warning
    - alert: ContainerMemoryToLimit
      annotations:
        message: container {{ $labels.container }} 的内存已达阈值的 {{ printf "%0.0f" $value }}%, 且持续10分钟
      expr: |-
        sum(label_replace(container_memory_working_set_bytes{namespace="prod", container_name!="POD", container_name!="", container_name!="istio-proxy"}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_memory_bytes{namespace="prod", container!="istio-proxy"}) by (container) * 100 > 85
      for: 30m
      labels:
        severity: warning
    - alert: ContainerMemoryToLimit
      annotations:
        message: container {{ $labels.container }} 的内存已达到阈值的 {{ printf "%0.0f" $value }}%, 且持续5分钟
      expr: |-
        sum(label_replace(container_memory_working_set_bytes{namespace="prod", container_name!="POD", container_name!="", container_name!="istio-proxy"}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_memory_bytes{namespace="prod", container!="istio-proxy"}) by (container) * 100 > 90
      for: 10m
      labels:
        severity: warning
    - alert: ContainerMemoryToLimit
      annotations:
        message: container {{ $labels.container }} 的内存已达到阈值的 {{ printf "%0.0f" $value }}%
      expr: |-
        sum(label_replace(container_memory_working_set_bytes{namespace="prod", container_name!="POD", container_name!="", container_name!="istio-proxy"}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_memory_bytes{namespace="prod", container!="istio-proxy"}) by (container) * 100 > 95
      labels:
        severity: critical
    - alert: ContainerCpuToLimit
      annotations:
        message: container {{ $labels.container }} 的cpu已达到阈值的 {{ printf "%0.0f" $value }}%, 且持续10分钟
      expr: |-
        sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace="prod",container_name!="POD",container_name!="istio-proxy",}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_cpu_cores{namespace="prod",container!="istio-proxy"}) by (container) * 100 > 85
      for: 30m
      labels:
        severity: warning
    - alert: ContainerCpuToLimit
      annotations:
        message: container {{ $labels.container }} 的cpu已达到阈值的 {{ printf "%0.0f" $value }}%, 且持续5分钟
      expr: |-
        sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace="prod",container_name!="POD",container_name!="istio-proxy",}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_cpu_cores{namespace="prod",container!="istio-proxy"}) by (container) * 100 > 90
      for: 10m
      labels:
        severity: warning
    - alert: ContainerCpuToLimit
      annotations:
        message: container {{ $labels.container }} 的cpu已达到阈值的 {{ printf "%0.0f" $value }}%
      expr: |-
        sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace="prod",container_name!="POD",container_name!="istio-proxy",}, "container", "$1", "container_name", "(.*)")) by (container) 
          / 
        sum(kube_pod_container_resource_limits_cpu_cores{namespace="prod",container!="istio-proxy"}) by (container) * 100 > 95
      labels:
        severity: critical




