apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-operator
  name: prometheus-operator-kube-prometheus-node-alerting.rules
  namespace: monitor
spec:
  groups:
  - name: kube-prometheus-node-alerting.rules
    rules:
    - alert: NodeDiskRunningFull
      annotations:
        message: Device {{ $labels.device }} of node-exporter {{ $labels.namespace
          }}/{{ $labels.pod }} will be full within the next 24 hours.
      expr: '(node:node_filesystem_usage: > 0.85) and (predict_linear(node:node_filesystem_avail:[6h],
        3600 * 24) < 0)'
      for: 30m
      labels:
        severity: warning
    - alert: NodeDiskRunningFull
      annotations:
        message: Device {{ $labels.device }} of node-exporter {{ $labels.namespace
          }}/{{ $labels.pod }} will be full within the next 2 hours.
      expr: '(node:node_filesystem_usage: > 0.85) and (predict_linear(node:node_filesystem_avail:[30m],
        3600 * 2) < 0)'
      for: 10m
      labels:
        severity: critical
    - alert: NodeDiskRunningFull
      annotations:
        message: instance {{ $labels.instance }} disk used more than 80%, duration is 5m, values is {{ $value }}
      expr: 'node:node_filesystem_usage: > 0.8'
      for: 5m
      labels:
        severity: warning
    - alert: NodeDiskRunningFull
      annotations:
        message: instance {{ $labels.instance }} disk used more than 90%, values is {{ $value }}
      expr: 'node:node_filesystem_usage: > 0.9'
      labels:
        severity: critical
    - alert: NodeMemoryRunningFull
      expr: sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance) > 0.8
      for: 3m
      labels:
        severity: warning
      annotations:
        message: instance {{ $labels.instance }} memory used more than 80%, duration is 3m, values is {{ $value }}
    - alert: NodeMemoryRunningFull
      expr: sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance) > 0.9
      labels:
        severity: critical
      annotations:
        message: instance {{ $labels.instance }} memory used more than 9%, values is {{ $value }}
    - alert: NodeCpuRunningFull
      expr: 'node:node_cpu_utilisation:avg1m > 0.8'
      for: 3m
      labels:
        severity: warning
      annotations:
        message: instance {{ $labels.instance }} cpu used more than 80%, duration is 3m, values is {{ $value }}
    - alert: NodeCpuRunningFull
      expr: 'node:node_cpu_utilisation:avg1m > 0.9'
      labels:
        severity: critical
      annotations:
        message: instance {{ $labels.instance }} cpu used more than 90%, values is {{ $value }}

