---

- name: check node_exporter log directory
  stat: path={{ node_exporter_log_dir }} get_md5=false get_checksum=false
  register: log_dir_st

- fail:
    msg: "{{ node_exporter_log_dir }} must exist and is a directory"
  when: log_dir_st.stat.isdir is not defined or log_dir_st.stat.isdir == False

- name: collect system log
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ node_exporter_log_dir }} --alias={{ inventory_hostname }} log --syslog --retention={{ collect_log_recent_hours | default('2') }}"
  become: true
