---

- name: download tidb docker images
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    archive_path: "{{ downloads_dir }}/{{ item.service }}.tar"
  with_items: "{{ tidb_images }}"
  when: has_outbound_network

- name: download third party docker images
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    archive_path: "{{ downloads_dir }}/{{ item.service }}.tar"
  with_items: "{{ third_party_images }}"
  when: has_outbound_network
