---
dummy:

# Tidb cluster information to import data
tidb_host: "{{ hostvars[groups.tidb_servers[0]].ansible_host | default(hostvars[groups.tidb_servers[0]].inventory_hostname) }}"
tidb_port: "{{ hostvars[groups.tidb_servers[0]].tidb_port }}"
tidb_user: "root"
tidb_password: ""
tidb_status_port: "{{ hostvars[groups.tidb_servers[0]].tidb_status_port }}"
