{
 "title": "Prod-Cluster-PD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pd_cluster_status, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pd_cluster_status{instance=\"$instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PD Role",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(pd_server_tso{type=\"save\",instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_capacity\"})"
    }
   ]
  },
  {
   "title": "Current Storage Size",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"storage_size\"})"
    }
   ]
  },
  {
   "title": "Number of Regions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\",namespace=~\"$namespace\",type=\"leader_count\"})"
    }
   ]
  },
  {
   "title": "Leader Balance Ratio",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - min(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_score\"}) / max(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_score\"})"
    }
   ]
  },
  {
   "title": "Region Balance Ratio",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - min(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_score\"}) / max(pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_score\"})"
    }
   ]
  },
  {
   "title": "Store Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"store_up_count\"})",
     "legendFormat": "Up Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_disconnected_count\"})",
     "legendFormat": "Disconnect Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_unhealth_count\"})",
     "legendFormat": "Unhealth Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_low_space_count\"})",
     "legendFormat": "LowSpace Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_down_count\"})",
     "legendFormat": "Down Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_offline_count\"})",
     "legendFormat": "Offline Stores"
    },
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\",type=\"store_tombstone_count\"})",
     "legendFormat": "Tombstone Stores"
    }
   ]
  },
  {
   "title": "Current Storage Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"storage_size\"}",
     "legendFormat": "strage size"
    },
    {
     "expr": "avg(pd_cluster_status{type=\"storage_size\", namespace=~\"$namespace\"}) / avg(pd_cluster_status{type=\"storage_capacity\", namespace=~\"$namespace\"})",
     "legendFormat": "used ratio"
    }
   ]
  },
  {
   "title": "Current Regions Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pd_cluster_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_count\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Metadata Information",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pd_cluster_metadata{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "99% Region Label Isolation Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_regions_label_level[5m])) by (le)) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Region Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pd_regions_status{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store leader score",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_score\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    },
    {
     "title": "Store region score",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_score\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_size\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    },
    {
     "title": "Store region size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_size\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"leader_count\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    },
    {
     "title": "Store region count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{instance=\"$instance\", namespace=~\"$namespace\", type=\"region_count\"}",
       "legendFormat": "tikv-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HotRegion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hot write region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_write_region_as_leader\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot write region's peer distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_write_region_as_peer\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot write region's leader written bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_written_bytes_as_leader\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot region's peer written bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_written_bytes_as_peer\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot read region's leader distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_read_region_as_leader\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot read region's peer distribution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"hot_read_region_as_peer\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot read region's leader read bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_read_bytes_as_leader\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Hot read region's peer read bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{instance=\"$instance\",type=\"total_read_bytes_as_peer\"}",
       "legendFormat": "{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler is running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_status{type=\"allow\",instance=\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Balance leader scheduler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-leader-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Balance region scheduler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_event_count{instance=\"$instance\", type=\"balance-region-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Namespace checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"namespace_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Replica checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"replica_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Region merge checker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_checker_event_count{instance=\"$instance\", type=\"merge_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedule operator create",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"create\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator check",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"check\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator finish",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"finish\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator timeout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"timeout\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator replaced",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\", event=\"replaced\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operators count by state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{instance=\"$instance\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "99% operator finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% operator finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% operator step finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "50% operator step finish duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket[5m])) by (type, le))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "completed commands rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_count{instance=\"$instance\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99% completed_cmds_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{instance=\"$instance\"}[5m])) by (grpc_method, le))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "handle_txns_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_txn_handle_txns_duration_seconds_count[5m])) by (instance, result)",
       "legendFormat": "{{instance}} : {{result}}"
      }
     ]
    },
    {
     "title": "99% handle_txns_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_txn_handle_txns_duration_seconds_bucket[5m])) by (instance, result, le))",
       "legendFormat": "{{instance}} {{result}}"
      }
     ]
    },
    {
     "title": "99% wal_fsync_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% peer_round_trip_time_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "etcd disk wal fsync rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_disk_wal_fsync_duration_seconds_count[1m])",
       "legendFormat": "{{instance}} etch disk wal fsync rate"
      }
     ]
    }
   ]
  },
  {
   "title": "TiDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "handle_requests_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "handle_requests_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket[30s])) by (type, le))",
       "legendFormat": "{{type}} 98th percentile"
      },
      {
       "expr": "avg(rate(pd_client_request_handle_requests_duration_seconds_sum[30s])) by (type) /  avg(rate(pd_client_request_handle_requests_duration_seconds_count[30s])) by (type)",
       "legendFormat": "{{type}} average"
      }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Region heartbeat report",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"ok\"}[1m])) by (store)",
       "legendFormat": "store{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"err\"}[1m])) by (store)",
       "legendFormat": "store{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{instance=\"$instance\", type=\"report\", status=\"bind\"}[1m])) by (store)",
       "legendFormat": "store{{store}}"
      }
     ]
    },
    {
     "title": "Region schedule push",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_region_heartbeat{type=\"push\",instance=\"$instance\"}[5m])*60) by (store, status)",
       "legendFormat": "store{{store}}-{{status}}"
      }
     ]
    },
    {
     "title": "99% region heartbeat latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_scheduler_region_heartbeat_latency_seconds_bucket[5m])) by (store, le))",
       "legendFormat": "store{{store}}"
      }
     ]
    }
   ]
  }
 ]
}