{
 "title": "Prod-Cluster-TiDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Query Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "80"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_server_query_total[1m])) by (result)",
     "legendFormat": "query {{result}}"
    }
   ]
  },
  {
   "title": "Statement Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_executor_statement_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tidb_server_query_total[1m])",
     "legendFormat": "{{instance}} {{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Query Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration 80 By Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 95 By Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Duration 99 By Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Duration 999 By Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_connections", "legendFormat": "{{instance}}" },
      { "expr": "sum(tidb_server_connections)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"tidb.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{job=~\"tidb.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Events",
     "type": "graph",
     "description": "TiDB Server events.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_event_total", "legendFormat": "{{instance}}-{{type}}" }
     ]
    },
    {
     "title": "Panic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_panic[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Keep Alive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_monitor_keep_alive_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_transaction_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "Statements Per Transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " histogram_quantile(0.99, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": " histogram_quantile(0.80, sum(rate(tidb_session_transaction_statement_num_bucket[30s])) by (le))",
       "legendFormat": "80"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Retry Error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_retry_error_total[30s]))",
       "legendFormat": "retry error"
      }
     ]
    },
    {
     "title": "Session Retry Counter",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_retry_num_bucket[30s])) by (le))"
      }
     ]
    },
    {
     "title": "Internal SQL Count",
     "type": "graph",
     "description": "The internal SQL is used by TiDB itself.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_session_restricted_sql_total[30s]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expensive Executors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_executor_expensive_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distsql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distsql Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_handle_query_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "50-{{type}}"
      }
     ]
    },
    {
     "title": "Distsql QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_distsql_handle_query_duration_seconds_count[1m]))"
      }
     ]
    },
    {
     "title": "Distsql Partial QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_distsql_scan_keys_partial_num_count[1m]))"
      }
     ]
    },
    {
     "title": "Scan Keys Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_scan_keys_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Scan Keys Partial Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_distsql_scan_keys_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Partial Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_distsql_partial_num_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Coprocessor Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_cop_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Coprocessor Seconds 999",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_cop_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "KV Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "KV Retry Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "9999"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (le))",
     "legendFormat": "80"
    }
   ]
  },
  {
   "title": "TiClient Region Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_region_err_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Backoff Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_backoff_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "LockResolve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Other Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tidb_tikvclient_lock_cleanup_task_total[1m])) by (type)",
     "legendFormat": "cleanup_secondary_failure_{{type}}"
    },
    {
     "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"fail\"}[1m]))",
     "legendFormat": "load_safepoint_failure"
    }
   ]
  },
  {
   "title": "KV Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Seconds 999 by store",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, store))",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "KV Request Seconds 999 by type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Seconds 9999",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Seconds 99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Cmd Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Txn Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "90 Txn Regions Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_tikvclient_txn_regions_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Txn Write Size Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_size_bytes_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Txn Write KV Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_kv_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Safepoint Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"ok\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "PD Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD Client CMD count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type!=\"tso\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 93 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\"}[1m])) by (le, type))",
       "legendFormat": "90-{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Fail",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 93 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_failed_cmds_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD TSO QPS",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "cmd"
      },
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count{type=\"tso\"}[1m]))",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "PD TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "PD TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client sending TSO request until received the response.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 100 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Schema Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_domain_load_schema_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load Schema QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_domain_load_schema_total[1m])) by (instance,type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Schema Lease Error Increase",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_session_schema_lease_error_total[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "DDL Duration 95th",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_ddl_handle_job_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Batch Add Index Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_batch_add_idx_succ_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "DDL Waiting Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_ddl_waiting_jobs[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "DDL Counter",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_ddl_worker_operation_total[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "DDL Worker Operation Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_ddl_worker_operation_duration_seconds_bucket[1m])) by (type, result)",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Deploy Syncer Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_deploy_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Owner Handle Syncer Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_owner_handle_syncer_duration_seconds_bucket[2m])) by (le, type, result))",
       "legendFormat": "{{type}}-{{result}}"
      }
     ]
    },
    {
     "title": "Update Self Version Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_ddl_update_self_ver_duration_seconds_bucket[2m])) by (le, result))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auto Analyze Seconds 95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_statistics_auto_analyze_duration_bucket[1m])) by (le))",
       "legendFormat": "auto analyze duration"
      }
     ]
    },
    {
     "title": "Auto Analyze QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_auto_analyze_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stats Inaccuracy Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tidb_statistics_stats_inaccuracy_rate_bucket[1m])) by (le))",
       "legendFormat": "50"
      }
     ]
    },
    {
     "title": "Pseudo Estimation Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_statistics_pseudo_estimation_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "AutoID QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_autoid_operation_duration_seconds_count[1m]))"
      }
     ]
    },
    {
     "title": "AutoID Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 125 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_autoid_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "80-{{type}}"
      }
     ]
    },
    {
     "title": "Meta Operations Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 125 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_meta_operation_duration_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Action Increase",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_worker_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_gc_seconds_bucket[1m])) by (le))"
      }
     ]
    },
    {
     "title": "Config",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(tidb_tikvclient_gc_config) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "GC Failure",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_failure[1m]))"
      }
     ]
    },
    {
     "title": "Action Result",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 133 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_gc_action_result[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Too Many Locks Error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 133 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tidb_tikvclient_gc_region_too_many_locks[1m]))"
      }
     ]
    }
   ]
  }
 ]
}