{
 "title": "Prod-Cluster-TiKV Instances",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(tikv_thread_cpu_seconds_total, instance)"
   },
   {
    "name": "store",
    "query": "label_values(tikv_thread_cpu_seconds_total{instance=~\"$instance\"}, job)"
   },
   {
    "name": "host",
    "query": "label_values(tikv_thread_cpu_seconds_total{job=\"$store\"}, instance)"
   },
   {
    "name": "db",
    "query": "label_values(tikv_engine_estimate_num_keys, db)"
   }
  ]
 },
 "panels": [
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_engine_size_bytes{job=\"$store\"}) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "tikv_store_size_bytes{job=\"$store\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Region count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_pd_heartbeat_tick_total{job=\"$store\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Keys flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_region_read_keys_sum{job=\"$store\"}[1m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(tikv_region_written_keys_sum{job=\"$store\"}[1m]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Bytes flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_region_read_bytes_sum{job=\"$store\"}[1m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(tikv_region_written_bytes_sum{job=\"$store\"}[1m]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Channel full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_channel_full_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Failure messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_server_report_failure_msg_total{job=\"$store\"}[1m])) by (type, store_id)",
       "legendFormat": "{{ type }} to {{ store_id }}"
      }
     ]
    },
    {
     "title": "Leader missing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tikv_raftstore_leader_missing{job=\"$store\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"grpc.*\"}[1m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_grpc_msg_fail_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }} - FAILED"
      }
     ]
    },
    {
     "title": "Request duration (average)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_sum{job=\"$store\"}[1m])) by (type) / sum(rate(tikv_grpc_msg_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Request duration (99%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Coprocessor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"endpoint.*\"}[1m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_request_duration_seconds_count{job=\"$store\",req=\"select\"}[1m]))",
       "legendFormat": "table"
      },
      {
       "expr": "sum(rate(tikv_coprocessor_request_duration_seconds_count{job=\"$store\",req=\"index\"}[1m]))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Request duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_coprocessor_request_duration_seconds_sum{job=\"$store\",req=\"select\"}[1m])) / sum(rate(tikv_coprocessor_request_duration_seconds_count{job=\"$store\",req=\"select\"}[1m]))",
       "legendFormat": "table"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_duration_seconds_sum{job=\"$store\",req=\"index\"}[1m])) / sum(rate(tikv_coprocessor_request_duration_seconds_count{job=\"$store\",req=\"index\"}[1m]))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Request duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{job=\"$store\",req=\"select\"}[1m])) by (le))",
       "legendFormat": "table"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{job=\"$store\",req=\"index\"}[1m])) by (le))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Wait duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_coprocessor_request_wait_seconds_sum{job=\"$store\",req=\"select\"}[1m])) /  sum(rate(tikv_coprocessor_request_wait_seconds_count{job=\"$store\",req=\"select\"}[1m]))",
       "legendFormat": "table"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_wait_seconds_sum{job=\"$store\",req=\"index\"}[1m])) /  sum(rate(tikv_coprocessor_request_wait_seconds_count{job=\"$store\",req=\"index\"}[1m]))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Wait duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{job=\"$store\",req=\"select\"}[1m])) by (le))",
       "legendFormat": "table"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{job=\"$store\",req=\"index\"}[1m])) by (le))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Handle duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_coprocessor_request_handle_seconds_sum{job=\"$store\",req=\"select\"}[1m])) /  sum(rate(tikv_coprocessor_request_handle_seconds_count{job=\"$store\",req=\"select\"}[1m]))",
       "legendFormat": "table"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_handle_seconds_sum{job=\"$store\",req=\"index\"}[1m])) /  sum(rate(tikv_coprocessor_request_handle_seconds_count{job=\"$store\",req=\"index\"}[1m]))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Handle duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{job=\"$store\",req=\"select\"}[1m])) by (le))",
       "legendFormat": "table"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{job=\"$store\",req=\"index\"}[1m])) by (le))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Request errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_request_error{job=\"$store\"}[1m])) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Pending requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_coprocessor_pending_request{job=\"$store\",req=\"select\"}",
       "legendFormat": "table - {{ priority }}"
      },
      {
       "expr": "tikv_coprocessor_pending_request{job=\"$store\",req=\"index\"}",
       "legendFormat": "index - {{ priority }}"
      }
     ]
    },
    {
     "title": "Executor count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_executor_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Get or scan count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_get_or_scan_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Scan keys (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_coprocessor_scan_keys_sum{job=\"$store\",req=\"select\"}[1m])) / sum(rate(tikv_coprocessor_scan_keys_count{job=\"$store\",req=\"select\"}[1m]))",
       "legendFormat": "table"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_scan_keys_sum{job=\"$store\",req=\"index\"}[1m])) / sum(rate(tikv_coprocessor_scan_keys_count{job=\"$store\",req=\"index\"}[1m]))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Scan keys (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_scan_keys_bucket{job=\"$store\",req=\"select\"}[1m])) by (le))",
       "legendFormat": "table"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_scan_keys_bucket{job=\"$store\",req=\"index\"}[1m])) by (le))",
       "legendFormat": "index"
      }
     ]
    },
    {
     "title": "Scan details",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_scan_details{job=\"$store\",req=\"select\"}[1m])) by (tag)",
       "legendFormat": "table - {{ tag }}"
      },
      {
       "expr": "sum(rate(tikv_coprocessor_scan_details{job=\"$store\",req=\"index\"}[1m])) by (tag)",
       "legendFormat": "index - {{ tag }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"storage_.*\"}[1m]))"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_command_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_storage_rawkv_command_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Async requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_engine_async_request_total{job=\"$store\",status=\"success\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Async request errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_engine_async_request_total{job=\"$store\",status!~\"all|success\"}[1m])) by (type,status)",
       "legendFormat": "{{ type }} - {{ status }}"
      }
     ]
    },
    {
     "title": "Async request duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_storage_engine_async_request_duration_seconds_sum{job=\"$store\"}[1m])) by (type) /  sum(rate(tikv_storage_engine_async_request_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Async request duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"sched_high_.*\"}[1m]))",
       "legendFormat": "high"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"sched_worker_.*\"}[1m]))",
       "legendFormat": "normal"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_scheduler_command_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_scheduler_too_busy_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }} - BUSY"
      }
     ]
    },
    {
     "title": "Request duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_command_duration_seconds_sum{job=\"$store\"}[1m])) by (type) /  sum(rate(tikv_scheduler_command_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Request duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_command_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Latch wait duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_latch_wait_duration_seconds_sum{job=\"$store\"}[1m])) by (type) /  sum(rate(tikv_scheduler_latch_wait_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Latch wait duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Read keys histogram (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_kv_command_key_read_sum{job=\"$store\"}[1m])) by (type) /  sum(rate(tikv_scheduler_kv_command_key_read_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Read keys histogram (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_kv_command_key_read_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Process read duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_processing_read_duration_seconds_sum{job=\"$store\"}[1m])) by (type) /  sum(rate(tikv_scheduler_processing_read_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Process read duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_processing_read_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Write keys histogram (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_kv_command_key_write_sum{job=\"$store\"}[1m])) by (type) / sum(rate(tikv_scheduler_kv_command_key_write_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Write keys histogram (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_kv_command_key_write_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Process write duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " sum(rate(tikv_scheduler_processing_write_duration_seconds_sum{job=\"$store\"}[1m])) by (type) / sum(rate(tikv_scheduler_processing_write_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Process write duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_processing_write_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Pending requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_scheduler_contex_total{job=\"$store\"}"
      }
     ]
    },
    {
     "title": "Pending write bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_scheduler_writing_bytes{job=\"$store\"}"
      }
     ]
    },
    {
     "title": "Scan details",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_scheduler_kv_scan_details{job=\"$store\"}[1m])) by (req, tag)",
       "legendFormat": "{{ req }} - {{ tag }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conflict conut",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_mvcc_conflict_counter{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Duplicated conut",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_mvcc_duplicate_cmd_counter{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "GC versions (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_mvcc_versions_sum{job=\"$store\"}[1m])) / sum(rate(tikv_storage_mvcc_versions_count{job=\"$store\"}[1m])) ",
       "legendFormat": "scan"
      },
      {
       "expr": "sum(rate(tikv_storage_mvcc_gc_delete_versions_sum{job=\"$store\"}[1m])) / sum(rate(tikv_storage_mvcc_gc_delete_versions_count{job=\"$store\"}[1m])) ",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "GC versions (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_storage_mvcc_versions_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "scan"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_storage_mvcc_gc_delete_versions_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "GC commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_storage_command_total{job=\"$store\",type=\"gc\"}[1m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(rate(tikv_storage_gc_empty_range_total{job=\"$store\"}[1m]))",
       "legendFormat": "empty"
      },
      {
       "expr": "sum(rate(tikv_storage_gc_skipped_counter{job=\"$store\"}[1m]))",
       "legendFormat": "skipped"
      }
     ]
    }
   ]
  },
  {
   "title": "Raftstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"raftstore_.*\"}[1m]))",
       "legendFormat": "raftstore"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"apply_worker\"}[1m]))",
       "legendFormat": "apply worker"
      }
     ]
    },
    {
     "title": "Handled readies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_raft_ready_handled_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Admin commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_admin_cmd_total{job=\"$store\",status=\"success\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_raftstore_admin_cmd_total{job=\"$store\",status!~\"all|success\"}[1m])) by (type, status)",
       "legendFormat": "{{ type }} - {{ status }}"
      }
     ]
    },
    {
     "title": "Proposed commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_proposal_total{job=\"$store\",type!=\"all\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Raft sent messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_raft_sent_message_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Raft dropped messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_raft_dropped_message_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Process tick duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{job=\"$store\",type=\"tick\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_raft_process_duration_secs_sum{job=\"$store\",type=\"tick\"}[1m])) / sum(rate(tikv_raftstore_raft_process_duration_secs_count{job=\"$store\",type=\"tick\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Process ready duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{job=\"$store\",type=\"ready\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_raft_process_duration_secs_sum{job=\"$store\",type=\"ready\"}[1m])) / sum(rate(tikv_raftstore_raft_process_duration_secs_count{job=\"$store\",type=\"ready\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Request wait duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_request_wait_time_duration_secs_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_request_wait_time_duration_secs_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Append log duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_append_log_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_append_log_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_append_log_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Apply log duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_log_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_apply_log_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_apply_log_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Apply wait duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_wait_time_duration_secs_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": " sum(rate(tikv_raftstore_apply_wait_time_duration_secs_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_apply_wait_time_duration_secs_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Raftstore - workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"snapshot_worker.*\"}[1m]))",
       "legendFormat": "snapshot"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"split_check.*\"}[1m]))",
       "legendFormat": "split check"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"compact_worker\"}[1m]))",
       "legendFormat": "compact range"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"consistency.*\"}[1m]))",
       "legendFormat": "consistency check"
      }
     ]
    },
    {
     "title": "Approximate region size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_region_size_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_region_size_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_region_size_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Handled tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_worker_handled_task_total{job=\"$store\",name=~\"snapshot worker\"}[1m]))",
       "legendFormat": "snapshot"
      },
      {
       "expr": "sum(rate(tikv_worker_handled_task_total{job=\"$store\",name=~\"split check worker\"}[1m]))",
       "legendFormat": "split check"
      },
      {
       "expr": "sum(rate(tikv_worker_handled_task_total{job=\"$store\",name=~\"compact worker\"}[1m]))",
       "legendFormat": "compact range"
      },
      {
       "expr": "sum(rate(tikv_worker_handled_task_total{job=\"$store\",name=~\"consistency check worker\"}[1m]))",
       "legendFormat": "consistency check"
      }
     ]
    },
    {
     "title": "Pending tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_worker_pending_task_total{job=\"$store\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Split check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_check_split_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Split check duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_check_split_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_check_split_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_check_split_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Compact range",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_compact_range_cf_duration_seconds_count{job=\"$store\"}[1m])) by (cf)",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Compact range duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_compact_range_cf_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_compact_range_cf_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_compact_range_cf_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Consistency check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_hash_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Consistency check duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_hash_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_hash_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_raftstore_hash_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Raftstore - snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"snapshot_worker\"}[1m]))"
      }
     ]
    },
    {
     "title": "Handled snapshots",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_server_send_snapshot_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "send"
      },
      {
       "expr": "sum(rate(tikv_raftstore_snapshot_total{job=\"$store\",status=\"success\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_raftstore_snapshot_total{job=\"$store\",status!~\"all|success\"}[1m])) by (type, status)",
       "legendFormat": "{{ type }} - {{ status }}"
      }
     ]
    },
    {
     "title": "State count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_raftstore_snapshot_traffic_total{job=\"$store\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Validation failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_snapshot_validation_failure_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Snapshot duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_server_send_snapshot_duration_seconds_sum{job=\"$store\"}[1m])) / sum(rate(tikv_server_send_snapshot_duration_seconds_count{job=\"$store\"}[1m]))",
       "legendFormat": "send"
      },
      {
       "expr": "sum(rate(tikv_raftstore_snapshot_duration_seconds_sum{job=\"$store\"}[1m])) by (type) / sum(rate(tikv_raftstore_snapshot_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Snapshot duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_server_send_snapshot_duration_seconds_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "send"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_snapshot_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Snapshot size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_snapshot_size_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_snapshot_size_sum{job=\"$store\"}[1m])) / sum(rate(tikv_snapshot_size_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Snapshot kv count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_snapshot_kv_count_bucket{job=\"$store\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "sum(rate(tikv_snapshot_kv_count_sum{job=\"$store\"}[1m])) / sum(rate(tikv_snapshot_kv_count_count{job=\"$store\"}[1m]))",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB - $db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "db",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"rocksdb.*\"}[1m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Stall duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 291 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Get count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 299 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m]))",
       "legendFormat": "memtable"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=~\"block_cache_data_hit|block_cache_filter_hit\"}[1m]))",
       "legendFormat": "block_cache"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l0\"}[1m]))",
       "legendFormat": "level 0"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l1\"}[1m]))",
       "legendFormat": "level 1"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l2_and_up\"}[1m]))",
       "legendFormat": "level 2 and up"
      }
     ]
    },
    {
     "title": "Get duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 299 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Seek count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 307 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_locate{job=\"$store\",db=\"$db\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Seek duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 307 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Write count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=\"write_with_wal\"}[1m]))",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=~\"write_done_by_self|write_done_by_other\"}[1m]))",
       "legendFormat": "done"
      },
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=\"write_timeout\"}[1m]))",
       "legendFormat": "timeout"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "WAL sync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_wal_file_synced{job=\"$store\",db=\"$db\"}[1m]))"
      }
     ]
    },
    {
     "title": "WAL sync duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "SST operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_opens\"}[1m]))",
       "legendFormat": "open"
      },
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_closes\"}[1m]))",
       "legendFormat": "close"
      },
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_errors\"}[1m]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "SST read duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 331 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Compaction count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_event_total{job=\"$store\",db=\"$db\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Compaction duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 339 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Memtable Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_memory_bytes{job=\"$store\",db=\"$db\",type=\"mem-tables\"}",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Memtable hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m])) / (sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m])) + sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_miss\"}[1m])))"
      }
     ]
    },
    {
     "title": "Block cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_block_cache_size_bytes{job=\"$store\",db=\"$db\"}",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Block cache operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 355 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_add\"}[1m]))",
       "legendFormat": "data add"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_add\"}[1m]))",
       "legendFormat": "index add"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_add\"}[1m]))",
       "legendFormat": "bloom filter add"
      }
     ]
    },
    {
     "title": "Block cache hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 363 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_miss\"}[1m])))",
       "legendFormat": "data"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_miss\"}[1m])))",
       "legendFormat": "index"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_miss\"}[1m])))",
       "legendFormat": "bloom filter"
      }
     ]
    },
    {
     "title": "Bloom filter hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 363 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_bloom_efficiency{job=\"$store\",db=\"$db\",type=\"bloom_prefix_useful\"}[1m])) / sum(rate(tikv_engine_bloom_efficiency{job=\"$store\",db=\"$db\",type=\"bloom_prefix_checked\"}[1m]))",
       "legendFormat": "bloom prefix"
      }
     ]
    },
    {
     "title": "Estimate keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_engine_estimate_num_keys{job=\"$store\",db=\"$db\"}) by (cf)",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Keys flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 371 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"keys_read\"}[1m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"keys_written\"}[1m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_num_corrupt_keys{job=\"$store\",db=\"$db\"}[1m]))",
       "legendFormat": "corrupt"
      }
     ]
    },
    {
     "title": "Read flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 379 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_read\"}[1m]))",
       "legendFormat": "get"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"iter_bytes_read\"}[1m]))",
       "legendFormat": "iterator"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_read\"}[1m]))",
       "legendFormat": "compaction"
      }
     ]
    },
    {
     "title": "Write flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 379 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"wal_file_bytes\"}[1m]))",
       "legendFormat": "WAL"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"flush_write_bytes\"}[1m]))",
       "legendFormat": "flush"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_written\"}[1m]))",
       "legendFormat": "compaction"
      }
     ]
    },
    {
     "title": "Compression ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 387 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_engine_compression_ratio{job=\"$store\",db=\"$db\",cf=~\"default|write\"}) by (level)",
       "legendFormat": "level - {{level}}"
      }
     ]
    },
    {
     "title": "Compaction pending  bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 387 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_pending_compaction_bytes{job=\"$store\",db=\"$db\"}[1m])) by (cf)",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Snapshot count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 395 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_num_snapshots{job=\"$store\",db=\"$db\"}"
      }
     ]
    },
    {
     "title": "Oldest snapshot duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 395 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_oldest_snapshot_duration{job=\"$store\",db=\"$db\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB - $db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"rocksdb.*\"}[1m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Stall duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 291 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_write_stall{job=\"$store\",db=\"$db\",type=\"write_stall_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Get count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 299 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m]))",
       "legendFormat": "memtable"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=~\"block_cache_data_hit|block_cache_filter_hit\"}[1m]))",
       "legendFormat": "block_cache"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l0\"}[1m]))",
       "legendFormat": "level 0"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l1\"}[1m]))",
       "legendFormat": "level 1"
      },
      {
       "expr": "sum(rate(tikv_engine_get_served{job=\"$store\",db=\"$db\",type=\"get_hit_l2_and_up\"}[1m]))",
       "legendFormat": "level 2 and up"
      }
     ]
    },
    {
     "title": "Get duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 299 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_get_micro_seconds{job=\"$store\",db=\"$db\",type=\"get_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Seek count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 307 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_locate{job=\"$store\",db=\"$db\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Seek duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 307 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_seek_micro_seconds{job=\"$store\",db=\"$db\",type=\"seek_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Write count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 315 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=\"write_with_wal\"}[1m]))",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=~\"write_done_by_self|write_done_by_other\"}[1m]))",
       "legendFormat": "done"
      },
      {
       "expr": "sum(rate(tikv_engine_write_served{job=\"$store\",db=\"$db\",type=\"write_timeout\"}[1m]))",
       "legendFormat": "timeout"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_write_micro_seconds{job=\"$store\",db=\"$db\",type=\"write_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "WAL sync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 323 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_wal_file_synced{job=\"$store\",db=\"$db\"}[1m]))"
      }
     ]
    },
    {
     "title": "WAL sync duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 323 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_wal_file_sync_micro_seconds{job=\"$store\",db=\"$db\",type=\"wal_file_sync_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "SST operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 331 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_opens\"}[1m]))",
       "legendFormat": "open"
      },
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_closes\"}[1m]))",
       "legendFormat": "close"
      },
      {
       "expr": "sum(rate(tikv_engine_file_status{job=\"$store\",db=\"$db\",type=\"no_file_errors\"}[1m]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "SST read duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 331 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_sst_read_micros{job=\"$store\",db=\"$db\",type=\"sst_read_micros_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Compaction count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 339 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_event_total{job=\"$store\",db=\"$db\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Compaction duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 339 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_percentile99\"}",
       "legendFormat": "99%"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_percentile95\"}",
       "legendFormat": "95%"
      },
      {
       "expr": "tikv_engine_compaction_time{job=\"$store\",db=\"$db\",type=\"compaction_time_average\"}",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Memtable Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 347 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_memory_bytes{job=\"$store\",db=\"$db\",type=\"mem-tables\"}",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Memtable hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 347 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m])) / (sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_hit\"}[1m])) + sum(rate(tikv_engine_memtable_efficiency{job=\"$store\",db=\"$db\",type=\"memtable_miss\"}[1m])))"
      }
     ]
    },
    {
     "title": "Block cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 355 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_block_cache_size_bytes{job=\"$store\",db=\"$db\"}",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Block cache operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 355 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_add\"}[1m]))",
       "legendFormat": "data add"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_add\"}[1m]))",
       "legendFormat": "index add"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_add\"}[1m]))",
       "legendFormat": "bloom filter add"
      }
     ]
    },
    {
     "title": "Block cache hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 363 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_data_miss\"}[1m])))",
       "legendFormat": "data"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_index_miss\"}[1m])))",
       "legendFormat": "index"
      },
      {
       "expr": "sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_hit\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{job=\"$store\",db=\"$db\",type=\"block_cache_filter_miss\"}[1m])))",
       "legendFormat": "bloom filter"
      }
     ]
    },
    {
     "title": "Bloom filter hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 363 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_bloom_efficiency{job=\"$store\",db=\"$db\",type=\"bloom_prefix_useful\"}[1m])) / sum(rate(tikv_engine_bloom_efficiency{job=\"$store\",db=\"$db\",type=\"bloom_prefix_checked\"}[1m]))",
       "legendFormat": "bloom prefix"
      }
     ]
    },
    {
     "title": "Estimate keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_engine_estimate_num_keys{job=\"$store\",db=\"$db\"}) by (cf)",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Keys flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 371 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"keys_read\"}[1m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"keys_written\"}[1m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_num_corrupt_keys{job=\"$store\",db=\"$db\"}[1m]))",
       "legendFormat": "corrupt"
      }
     ]
    },
    {
     "title": "Read flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 379 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_read\"}[1m]))",
       "legendFormat": "get"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"iter_bytes_read\"}[1m]))",
       "legendFormat": "iterator"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_read\"}[1m]))",
       "legendFormat": "compaction"
      }
     ]
    },
    {
     "title": "Write flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 379 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"wal_file_bytes\"}[1m]))",
       "legendFormat": "WAL"
      },
      {
       "expr": "sum(rate(tikv_engine_flow_bytes{job=\"$store\",db=\"$db\",type=\"flush_write_bytes\"}[1m]))",
       "legendFormat": "flush"
      },
      {
       "expr": "sum(rate(tikv_engine_compaction_flow_bytes{job=\"$store\",db=\"$db\",type=\"bytes_written\"}[1m]))",
       "legendFormat": "compaction"
      }
     ]
    },
    {
     "title": "Compression ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 387 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_engine_compression_ratio{job=\"$store\",db=\"$db\",cf=~\"default|write\"}) by (level)",
       "legendFormat": "level - {{level}}"
      }
     ]
    },
    {
     "title": "Compaction pending  bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 387 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_engine_pending_compaction_bytes{job=\"$store\",db=\"$db\"}[1m])) by (cf)",
       "legendFormat": "{{ cf }}"
      }
     ]
    },
    {
     "title": "Snapshot count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 395 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_num_snapshots{job=\"$store\",db=\"$db\"}"
      }
     ]
    },
    {
     "title": "Oldest snapshot duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 395 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "tikv_engine_oldest_snapshot_duration{job=\"$store\",db=\"$db\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 396 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"pd_0\"}[1m]))",
       "legendFormat": "pd client"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"pd_worker\"}[1m]))",
       "legendFormat": "pd worker"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{job=\"$store\",name=~\"store_address_r\"}[1m]))",
       "legendFormat": "store address"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 396 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_request_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "sum(rate(tikv_server_resolve_store_total{job=\"$store\"}[1m]))",
       "legendFormat": "resolve store"
      }
     ]
    },
    {
     "title": "Request duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 404 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_request_duration_seconds_sum{job=\"$store\"}[1m])) by (type) / sum(rate(tikv_pd_request_duration_seconds_count{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Request duration (99%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 404 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_pd_request_duration_seconds_bucket{job=\"$store\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Heartbeat messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 412 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_heartbeat_message_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Validate peer count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 412 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_validate_peer_total{job=\"$store\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  }
 ]
}