{
 "title": "Prod-Cluster-Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(pd_cluster_status, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual CPUs",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"user\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "node_memory_MemTotal", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU Usage(sum)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (irate(node_cpu{mode=\"idle\"}[1m]) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "TCP Retrans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans[1m])",
     "legendFormat": "{{instance}} - TCPSynRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSlowStartRetrans[1m])",
     "legendFormat": "{{instance}} - TCPSlowStartRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPForwardRetrans[1m])",
     "legendFormat": "{{instance}} - TCPForwardRetrans"
    }
   ]
  },
  {
   "title": "I/O Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin[5s]) * 1024 or irate(node_vmstat_pgpgin[5m]) * 1024",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "rate(node_vmstat_pgpgout[5s]) * 1024 or irate(node_vmstat_pgpgout[5m]) * 1024",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  {
   "title": "IO Util",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms[1m]) / 1000",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "PD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "PD Role",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "delta(pd_server_tso{type=\"save\",instance=\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "Storage Capacity",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 30 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"storage_capacity\"}"
      }
     ]
    },
    {
     "title": "Current Storage Size",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 10, "y": 30 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"storage_size\"}"
      }
     ]
    },
    {
     "title": "Number of Regions",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"region_count\"}"
      }
     ]
    },
    {
     "title": "Store Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 30 },
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_up_count\"}",
       "legendFormat": "Up Stores"
      },
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_disconnected_count\"}",
       "legendFormat": "Disconnect Stores"
      },
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_low_space_count\"}",
       "legendFormat": "LowSpace Stores"
      },
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_down_count\"}",
       "legendFormat": "Down Stores"
      },
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_offline_count\"}",
       "legendFormat": "Offline Stores"
      },
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"store_tombstone_count\"}",
       "legendFormat": "Tombstone Stores"
      }
     ]
    },
    {
     "title": "Current Storage Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"storage_size\"}",
       "legendFormat": "strage size"
      },
      {
       "expr": "avg(pd_cluster_status{type=\"storage_size\"}) / avg(pd_cluster_status{type=\"storage_capacity\"})",
       "legendFormat": "used ratio"
      }
     ]
    },
    {
     "title": "Current Regions Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"region_count\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Leader Balance Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"leader_balance_ratio\"}",
       "legendFormat": "leader max diff ratio"
      }
     ]
    },
    {
     "title": "Region Balance Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"region_balance_ratio\"}",
       "legendFormat": "\bstore balance ratio"
      }
     ]
    },
    {
     "title": "average completed_cmds_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_server_handling_seconds_sum{instance=\"$instance\"}[30s]) / rate(grpc_server_handling_seconds_count{instance=\"$instance\"}[30s])",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "tidb_handle_requests_duration_seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(pd_client_request_handle_requests_duration_seconds_sum[30s])) by (type) /  avg(rate(pd_client_request_handle_requests_duration_seconds_count[30s])) by (type)",
       "legendFormat": "{{type}} average"
      }
     ]
    },
    {
     "title": "Region heartbeat",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_region_heartbeat{instance=\"$instance\"}[1m])) by (store, type, status)",
       "legendFormat": "store{{store}}-{{type}}-{{status}}"
      }
     ]
    },
    {
     "title": "Leader Balance Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_cluster_status{instance=\"$instance\",type=\"leader_balance_ratio\"}",
       "legendFormat": "leader max diff ratio"
      }
     ]
    }
   ]
  },
  {
   "title": "TiDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tidb_server_query_total[1m])",
       "legendFormat": "{{instance}} {{type}} {{status}}"
      }
     ]
    },
    {
     "title": "QPS Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_server_query_total[1m])) by (status)",
       "legendFormat": "query {{status}}"
      },
      {
       "expr": "sum(rate(tidb_server_query_total{status=\"OK\"}[1m]  offset 1d))",
       "legendFormat": "yesterday"
      }
     ]
    },
    {
     "title": "Average Query Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(tidb_server_handle_query_duration_seconds_sum[30s]) / irate(tidb_server_handle_query_duration_seconds_count[30s])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(irate(tidb_server_handle_query_duration_seconds_sum[30s])) / sum(irate(tidb_server_handle_query_duration_seconds_count[30s]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Query Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Statement Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(tidb_executor_statement_node_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "tidb_server_connections", "legendFormat": "{{instance}}" },
      { "expr": "sum(tidb_server_connections)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"tidb.*\"}",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "KV Cmd Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_cmd_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Retry Seconds 9999",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_backoff_seconds_bucket[1m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "KV Request Seconds 9999",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_request_seconds_bucket[1m])) by (le, instance, type))",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Seconds 99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_seconds_bucket[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "TiClient Region Error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_region_err_total[1m])) by (type, instance)",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "LockResolve",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Load Schema Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "tidb_domain_load_schema_duration_sum / tidb_domain_load_schema_duration_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "KV Backoff Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_backoff_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiKV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "leader",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_pd_heartbeat_tick_total{type=\"leader\"}) by (instance,job)",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "region",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_pd_heartbeat_tick_total{type=\"region\"}) by (job,instance)",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    },
    {
     "title": "store size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_engine_size_bytes) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "active written leaders",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_region_written_keys_count[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "channel full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_channel_full_total[1m])) by (job, type)",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "server report failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_server_report_failure_msg_total[1m])) by (type,instance,job,store_id)",
       "legendFormat": "{{job}} - {{type}} - to - {{store_id}}"
      }
     ]
    },
    {
     "title": "scheduler pending commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_scheduler_contex_total) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "coprocessor pending requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_coprocessor_pending_request[1m])) by (req, priority)",
       "legendFormat": "{{ req }} - {{priority}}"
      }
     ]
    },
    {
     "title": "coprocessor table request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{req=\"select\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{req=\"select\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_duration_seconds_sum{req=\"select\"}[1m])) /  sum(rate(tikv_coprocessor_request_duration_seconds_count{req=\"select\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "coprocessor table wait duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{req=\"select\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{req=\"select\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_wait_seconds_sum{req=\"select\"}[1m])) /  sum(rate(tikv_coprocessor_request_wait_seconds_count{req=\"select\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "coprocessor index request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{req=\"index\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{req=\"index\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "sum(rate(tikv_coprocessor_request_duration_seconds_sum{req=\"index\"}[1m])) / sum(rate(tikv_coprocessor_request_duration_seconds_count{req=\"index\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "coprocessor index wait duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{req=\"index\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{req=\"index\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": " sum(rate(tikv_coprocessor_request_wait_seconds_sum{req=\"index\"}[1m])) /  sum(rate(tikv_coprocessor_request_wait_seconds_count{req=\"index\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "raft store CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{name=~\"raftstore_.*\"}[1m])) by (job, name)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "coprocessor CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{name=~\"endpoint.*\"}[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "PD request duration (average)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_request_duration_seconds_sum[1m])) by (type) / sum(rate(tikv_pd_request_duration_seconds_count[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  }
 ]
}