---

- name: test
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - include_vars:
        file: "{{ playbook_dir }}/vars.yml"
  tasks:
    - name: host facts
      ec2_remote_facts:
        filters:
          "tag:ManagedBy": "{{ managed_by }}"
        region: cn-north-1
      register: ec2_instances

    - name: add hosts
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: sre-to-be-teardown
      with_items: "{{ ec2_instances.instances }}"
      #when: ec2_instances.skipped | defined and not ec2_instances.skipped

    - debug: var=groups['sre-to-be-teardown']

    - pause: prompt="Are you sure to tear these down(C to continue, A to Abort)?"

- name: EC2 Instances
  hosts: sre-to-be-teardown
  gather_facts: false
  tasks:
    - name: gather facts
      ec2_facts:

    - name: Terminate instances that were previously launched
      delegate_to: localhost
      ec2:
        state: 'absent'
        instance_ids: '{{ ansible_ec2_instance_id }}'
        region: cn-north-1
        wait: yes
        wait_timeout: 500

- name: AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: terminate security group
      ec2_group:
        name: "ansible-sg-by-{{ managed_by }}"
        description: vpc security group by {{ creator }}
        region: cn-north-1
        state: absent

    - debug: msg="we do not terminate vpc :)"

