---

- include_tasks: binary_deployment.yml

- name: create configuration file
  copy: src="{{ playbook_dir }}/conf/grafana_collector.toml" dest="{{ deploy_dir }}/conf/grafana_collector.toml" mode=0644 backup=yes
  register: grafana_collector_conf_st

- name: backup conf file
  command: mv "{{ grafana_collector_conf_st.backup_file }}" "{{ backup_dir }}"
  when: grafana_collector_conf_st.changed and grafana_collector_conf_st.backup_file is defined

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [grafana_collector_port ~ '/tcp'] + firewalld_ports }}"
