---

- set_fact:
    collector_dir: "{{ hostvars[groups.monitored_servers[0]].deploy_dir }}"
    service_host: "{{ ansible_host }}"

- name: create pump fetch directory
  delegate_to: localhost
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ fetch_tmp_dir }}/{{ service_host }}"

- include_tasks: collect_log.yml

- name: compress collected data
  shell: "python {{ collector_dir }}/scripts/tidb-insight/insight.py --output={{ pump_log_dir }} --alias=pump_{{ inventory_hostname }} archive"

- name: fetch pump diagnosis tarball with bandwidth limit
  delegate_to: localhost
  shell: "scp -P {{ ansible_port|default(22) }} -l {{ collect_bandwidth_limit|default('10000') }} -o StrictHostKeyChecking=no {{ service_host }}:{{ pump_log_dir }}/pump_{{ inventory_hostname }}.tar.gz {{ fetch_tmp_dir }}/{{ service_host }}/pump_{{ inventory_hostname }}.tar.gz"
  when: enable_bandwidth_limit|default(true)

- name: fetch pump diagnosis tarball without bandwidth limit
  fetch:
    src: "{{ pump_log_dir }}/pump_{{ inventory_hostname }}.tar.gz"
    dest: "{{ fetch_tmp_dir }}/{{ service_host }}/pump_{{ inventory_hostname }}.tar.gz"
    flat: yes
  when: not enable_bandwidth_limit|default(true)

- name: remove pump temporary diagnosis tarball
  file:
    path: "{{ pump_log_dir }}/{{ item }}"
    state: absent
  with_items:
    - "pump_{{ inventory_hostname }}.tar.gz"
