{
 "title": "Single",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": "label_values(kube_service_labels{namespace=\"prod\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"prod\",container_name=\"$service\"}[1m])",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"prod\",container=\"$service\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Throttled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"prod\",container_name=\"$service\"}[1m])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"prod\",container_name=\"$service\"}",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"prod\",container=\"$service\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Usage - Istio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"prod\",pod_name=~\"$service.*\",container_name=\"istio-proxy\"}",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"prod\",container=\"istio-proxy\",pod=~\"$service.*\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "POD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runing",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_running{namespace=\"prod\",container=\"$service\"})"
      }
     ]
    },
    {
     "title": "Expect",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(kube_deployment_spec_replicas{namespace=\"prod\",deployment=~\"$service.*\"})"
      }
     ]
    },
    {
     "title": "Waiting",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(kube_pod_container_status_waiting{namespace=\"prod\",container=\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"prod\",destination_app=\"$service\",reporter=\"destination\",response_code=\"200\"}[1m]))"
      }
     ]
    },
    {
     "title": "Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"prod\",destination_app=\"$service\",response_code!=\"200\"}[1m])) by (reporter, response_flags)",
       "legendFormat": "{{reporter}}-{{response_flags}}"
      }
     ]
    }
   ]
  }
 ]
}