apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operator-prometheus:9090/
      access: proxy
      isDefault: true
    - name: Secondary
      type: prometheus
      url: http://172.16.50.9:9090/
      access: proxy
      isDefault: false
kind: ConfigMap
metadata:
  labels:
    app: prometheus-operator-grafana
    chart: prometheus-operator-6.21.0
    grafana_datasource: "1"
    heritage: Tiller
    release: prometheus-operator
  name: prometheus-operator-grafana-datasource
  namespace: monitor
